### ISSUE TITLE
__assign is not a function

### ISSUE THREAD

**Issue by michelson** [theKashey/use-sidecar#13]
Hi, I'm using version 1.0.1 and I've found a rare issue embedding the script into a site, the error is:

`TypeError: __assign is not a function at createSidecarMedium 
`
<img width="1440" alt="Screen Shot 2023-01-11 at 12 38 52" src="https://user-images.githubusercontent.com/11976/211849172-6bab7959-bb68-4162-9eda-16616b28679c.png">

the build is made with esbuild with target es2020

it seems that the assign function does not exist., and it is supposed that the assign is a function that is loaded from.

any idea what could be causing this?

**Comment by theKashey** [comment]
That is `tslib_1.__assign` (the end of https://unpkg.com/browse/use-sidecar@1.0.1/dist/es5/medium.js) and dependency on tslib is explicitly set.
So 🤷‍♂️, it should work
